export interface ProductDetailExtra {
  chipType: string;
  beamAngle: string;
  diameterMm: number;
  heightSingleMm: number;
  heightDualMm?: number;
  weightSingleG?: number;
  weightDualG?: number;
  startupPowerW: number;
  stablePowerW: number;
  startupLumen: number;
  stableLumen: number;
  h4StartupPowerW?: number;
  h4StablePowerW?: number;
  h4StartupLumen?: number;
  h4StableLumen?: number;
  ipRate: string;
  packagingBox: string;
  cartonBox: string;
  features: string[];
}

export const PRODUCT_DETAILS: Record<string, ProductDetailExtra> = {
  'PD-V7': {
    chipType: '3570-6 CSP',
    beamAngle: '270°',
    diameterMm: 35,
    heightSingleMm: 73,
    heightDualMm: 76.5,
    startupPowerW: 75,
    stablePowerW: 55,
    startupLumen: 6000,
    stableLumen: 4600,
    h4StartupPowerW: 60,
    h4StablePowerW: 50,
    h4StartupLumen: 5500,
    h4StableLumen: 4300,
    ipRate: 'IP67',
    packagingBox: 'Color Box 18×12×5cm / 0.3KG per set',
    cartonBox: 'Carton 62×38×27cm / 16KG / 50 sets per carton',
    features: [
      'Classic best-selling model with great value',
      'Dual copper pipes for efficient heat dissipation',
      'Chip temperature controlled below 110°C',
      'High lumen output with excellent value',
      'Long lifespan and stable performance',
      'Supports brightness adjustment',
    ],
  },
  'PD-X20': {
    chipType: '3570-9 CSP',
    beamAngle: '270°',
    diameterMm: 35,
    heightSingleMm: 73,
    heightDualMm: 76.5,
    startupPowerW: 80,
    stablePowerW: 60,
    startupLumen: 6500,
    stableLumen: 5500,
    h4StartupPowerW: 65,
    h4StablePowerW: 55,
    h4StartupLumen: 5500,
    h4StableLumen: 4800,
    ipRate: 'IP68',
    packagingBox: 'Color Box 21×15.5×5.5cm / 0.4KG per set',
    cartonBox: 'Carton 63×44×29.5cm / 17KG / 40 sets per carton',
    features: [
      'DC 10-60V ultra-wide voltage design',
      'Compatible with both passenger cars and trucks',
      'Dual copper pipes for heat dissipation',
      '9-core CSP LED chip for high brightness',
      'Stable output under voltage fluctuations',
      'Supports brightness adjustment',
    ],
  },
  'X50S': {
    chipType: '5080-6 CSP (Tri-Color Chip)',
    beamAngle: '270°',
    diameterMm: 40,
    heightSingleMm: 74,
    heightDualMm: 76,
    weightSingleG: 117,
    weightDualG: 130,
    startupPowerW: 105,
    stablePowerW: 60,
    startupLumen: 8000,
    stableLumen: 5000,
    h4StartupPowerW: 100,
    h4StablePowerW: 60,
    h4StartupLumen: 8000,
    h4StableLumen: 5000,
    ipRate: 'IP67',
    packagingBox: 'Color Box 21×15.5×5.5cm / 0.4KG per set',
    cartonBox: 'Carton 63×44×29.5cm / 17KG / 40 sets per carton',
    features: [
      'Three color temperatures in one bulb',
      '6500K Cool White / 4300K Warm White / 3000K Golden Yellow',
      'Remote control for easy in-car switching',
      'Suitable for sunny, rainy, and foggy conditions',
      'Triple copper pipes for efficient cooling',
      '5080 CSP high-brightness chip',
      'H4 model: low beam tri-color, high beam white',
    ],
  },
  'X50': {
    chipType: '5080-15 CSP',
    beamAngle: '270°',
    diameterMm: 40,
    heightSingleMm: 74,
    heightDualMm: 76,
    startupPowerW: 180,
    stablePowerW: 105,
    startupLumen: 15000,
    stableLumen: 8500,
    h4StartupPowerW: 110,
    h4StablePowerW: 75,
    h4StartupLumen: 11000,
    h4StableLumen: 6500,
    ipRate: 'IP67',
    packagingBox: 'Color Box 21×15.5×5.5cm / 0.4KG per set',
    cartonBox: 'Carton 63×44×29.5cm / 17KG / 40 sets per carton',
    features: [
      '15-core 5080 CSP premium LED chips',
      'Startup luminous flux up to 15,000lm',
      '25% brighter than standard models',
      '6.25% higher stable lumen output',
      'Flagship lighting performance',
      'Dual copper pipe heat dissipation',
    ],
  },
  'PD-X60': {
    chipType: '5080-12 CSP (single), 4575-15 CSP (H4 dual)',
    beamAngle: '270°',
    diameterMm: 38,
    heightSingleMm: 82.6,
    heightDualMm: 85.6,
    weightSingleG: 190,
    weightDualG: 198,
    startupPowerW: 135,
    stablePowerW: 85,
    startupLumen: 12000,
    stableLumen: 8000,
    h4StartupPowerW: 110,
    h4StablePowerW: 70,
    h4StartupLumen: 10000,
    h4StableLumen: 6000,
    ipRate: 'IP68',
    packagingBox: 'Color Box 21×15.5×5.5cm / 0.55KG per set',
    cartonBox: 'Carton 63×44×29.5cm / 22KG / 40 sets per carton',
    features: [
      'Flagship series with die-cast one-piece housing',
      'High thermal conductivity die-cast aluminum body',
      '5080 CSP 12-core LED chips',
      '12,000lm startup brightness',
      'Chip temperature controlled below 120°C',
      'Light efficiency up to 100lm/W',
      'IP68 waterproof rating',
      'Supports brightness adjustment',
    ],
  },
  'Z8': {
    chipType: '3570-8 CSP',
    beamAngle: '360°',
    diameterMm: 20,
    heightSingleMm: 50,
    startupPowerW: 35,
    stablePowerW: 28,
    startupLumen: 3500,
    stableLumen: 2900,
    h4StartupPowerW: 32,
    h4StablePowerW: 24,
    h4StartupLumen: 3300,
    h4StableLumen: 2300,
    ipRate: 'IP68',
    packagingBox: 'Color Box 9×8×4.8cm / 0.05KG per set',
    cartonBox: 'Carton 48×26×35cm / 100 sets per carton',
    features: [
      'Plug-and-play design, easy installation',
      'Built-in fan for active cooling',
      'Compact size fits most vehicles',
      '8-core CSP LED chip',
      '100-set bulk package, great value',
      'Lightweight design',
    ],
  },
  'PD-Z9': {
    chipType: '3570-6 CSP',
    beamAngle: '360°',
    diameterMm: 18,
    heightSingleMm: 45,
    weightSingleG: 14,
    startupPowerW: 22,
    stablePowerW: 9,
    startupLumen: 2000,
    stableLumen: 900,
    ipRate: 'IP68',
    packagingBox: 'Color Box 9×8×4.8cm / 0.1KG per set',
    cartonBox: 'Carton 48×26×35cm / 11KG / 100 sets per carton',
    features: [
      'Graphene cooling technology',
      'Fanless design — zero noise',
      'Ultra-lightweight, only 14g',
      'Plug-and-play installation',
      'IP68 waterproof rating',
      '100-set bulk package',
      'Great value entry-level model',
    ],
  },
  'PD-Z10': {
    chipType: '3570-6 CSP',
    beamAngle: '360°',
    diameterMm: 20,
    heightSingleMm: 48,
    weightSingleG: 18,
    startupPowerW: 30,
    stablePowerW: 18,
    startupLumen: 2800,
    stableLumen: 1800,
    ipRate: 'IP68',
    packagingBox: 'Color Box 9×8×4.8cm / 0.1KG per set',
    cartonBox: 'Carton 48×26×35cm / 11KG / 100 sets per carton',
    features: [
      'Graphene cooling + fan dual cooling system',
      'Ultra-lightweight, only 18g',
      '40% brighter than Z9 model',
      'Plug-and-play installation',
      'IP68 waterproof rating',
      '100-set bulk package',
      'Excellent value for money',
    ],
  },
};

export function getProductDetail(model: string): ProductDetailExtra | undefined {
  return PRODUCT_DETAILS[model];
}
